version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=your_database
            - DB_USERNAME=root
            - DB_PASSWORD=root
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: >
            sh -c "
              composer install &&
              npm install &&
              php artisan migrate &&
              npm run dev
            "

    db:
        image: mysql:5.7
        container_name: my_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: your_database
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    dbdata:
